apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-demo
      version: v2
  template:
    metadata:
      labels:
        app: canary-demo
        version: v2
    spec:
      containers:
        - name: canary-demo
          image: docker.io/azimulayaz/canary-demo:app-v2
          ports:
            - containerPort: 8080
